firstmap:
set image nothing
set map firstmap
make object fighter thehero
set object thehero
say If you want to interact with anything, just press [Enter] while facing it.

loadgame:
// loadgame

start:
set image title800x600.jpg
choicetitle
choice a New Game
choice b Load Game
choice c Exit
for a
goto firstmap
end
for b
goto loadgame
end
for c
exitgame
end
say You have made your choice! Congratulations
